### ISSUE TITLE
Overlapping buttons

### ISSUE THREAD

**Issue by Freeplayg** [100photos/scultradark#1]
![2021-04-27_19-19_1](https://user-images.githubusercontent.com/40742947/116324214-b55e1000-a78d-11eb-93ac-3689e67254d3.png)
![2021-04-27_19-22](https://user-images.githubusercontent.com/40742947/116324325-efc7ad00-a78d-11eb-8350-144cea4a7c63.png)

**Comment by JunkiEDM** [comment]
Yeah I've been trying to sort out how to best solve this without rearranging things too much but I think I'll end up just moving the navigation down below the banner anyways.
Could I ask what Browser/OS you're using though? Although its not related to the issue the navbar shouldn't be that far to the right, this is what it looks like on my end with the same width (Windows 10, Brave Dev 1.24.77 / Chromium 90.0.4430.85)
![image](https://user-images.githubusercontent.com/8350274/116711493-46f59980-a9a9-11eb-8767-13d76ac10891.png)

**Comment by Freeplayg** [comment]
I'm using Firefox 88.0 64-bit on Pop! OS (Based on Ubuntu)
I was going to check on a chromium browser but it seems you've already updated the style
