### ISSUE TITLE
Weird interactions while keyboard shortcuts are open

### ISSUE THREAD

**Issue by DatHypnoboi** [100photos/scultradark#17]
When you open the keyboard shortcuts overlay, the rest of the site is darkened and blurred, but the player bar on the bottom isn't. If you then press q to open next up, the player will be darkened but not blurred. Pressing q again to close next up will briefly undarken and unblur next up as it plays the closing animation, and it will display over the keyboard shortcuts overlay. The player will also return to being undarkened once next up is closed.

**Comment by JunkiEDM** [comment]
Yeah I know it's not pretty, it works this way to avoid overlapping as reported in #12. Besides, interacting with the queue will close any modals like add to playlist or keyboard shortcuts anyways so there's no functional benefit to have it show on top of them. It's ugly but it works.
