### ISSUE TITLE
Infinite loading when scrolling to the bottom

### ISSUE THREAD

**Issue by 1011025m** [100photos/scultradark#3]
SoundCloud always puts a loading gif at the bottom of the page to indicate that there are more tracks to be loaded (whether you have scrolled to the bottom or not)

There seems to be a height detection mechanism that prevents more tracks from loading when using the userstyle, will look into it.

**Comment by 1011025m** [comment]
Do you encounter the same issue on your end?

**Comment by JunkiEDM** [comment]
No I don't get this issue. What Browser & theme version do you have?
![image](https://user-images.githubusercontent.com/8350274/152183747-c53a3b82-0139-44f9-8ddf-036843842e1d.png)

**Comment by 1011025m** [comment]
Browser: Firefox Developer Edition v97.0b9
Theme version: v0.9.161

1080p canvases work fine, but I'm using a 1440p monitor. That's probably the issue.

**Comment by 1011025m** [comment]
Seems like a problem on my end. #4
