### ISSUE TITLE
Get soundcloud premium issue

### ISSUE THREAD

**Issue by tadghh** [100photos/scultradark#7]
The get soundcloud premium appear overtop of the username of the logged in user.

![image](https://user-images.githubusercontent.com/47073445/193449958-5d5f6bd4-d241-4432-a1f0-4568401bea12.png)

**Comment by tadghh** [comment]
Fixed in fork

**Comment by tadghh** [comment]
Add me as contributor and merge my repo >:(

**Comment by JunkiEDM** [comment]
I fixed this specific issue in https://github.com/JunkiEDM/scultradark/commit/499f99369c0c62e33c48f548ee6c53e84ce5ba18 in a slightly different way but forgot to close this issue.
I don't use git enough to know how to pull https://github.com/tadghh/scultradark/commit/ec719eac269fdc3f7055bfbea9dc9050e8db7d9f independently of your fork's other changes, but I credited you in the author tag for your help.

**Comment by JunkiEDM** [comment]
If anything else comes up that you want to update or improve, make a PR and I'll try to review it sooner than I did with this issue and to get your changes credited properly, sorry
