### ISSUE TITLE
The "Next Up" is located under the line with the control of the current track

### ISSUE THREAD

**Issue by lzrdblzzrd** [100photos/scultradark#9]
![image](https://user-images.githubusercontent.com/32615368/218300464-a56ef66b-19e5-4597-abde-9ba56fd203c1.png)

I think it's worth changing the z-index for this window a little so that it is slightly higher.

**Comment by lzrdblzzrd** [comment]
I also noticed that if the chat with the user is too large, then the "Add track or playlist" and "Send" buttons are also hidden under the track control bar.

If the chat is not large:
![image](https://user-images.githubusercontent.com/32615368/218300885-bf41374a-9536-49da-8808-ecdcc9587d2e.png)

If the chat is large:
![image](https://user-images.githubusercontent.com/32615368/218300907-37aa16d5-a87a-437e-9b9e-73ee81cb7cd4.png)

**Comment by JunkiEDM** [comment]
should be fixed in https://github.com/JunkiEDM/scultradark/commit/4df249e6b468c72dcb09c636bc8edaf3062ac51b
